### PR TITLE
Env/1730546425

### PR DESCRIPTION
**Pull request by eswar-sai-javvaji**
Updated the project with the given tigers way - project structure by dividing the script to 3 parts and adding config and logging features and user argument power. Also added two testing files, which need to run at starting to ensure code will run without errors.

### CODE REVIEW

**Review by Karthikeyaan-Kan — COMMENTED** [review]
1. Generate Sphinx Documentation for project and add ZIP file with HTML documentation

**Comment by eswar-sai-javvaji** [comment]
added that in classroom, is that file okay..?

**Comment by Karthikeyaan-Kan** [comment]
Could you add it in the PR?

**Comment by eswar-sai-javvaji** [comment]
[html_mlep.zip](https://github.com/eswar-sai-javvaji/mlep_modules/files/11592614/html_mlep.zip)
Hope this is enough

**Review by Karthikeyaan-Kan — APPROVED** [review]
The PR is approved

**Pull request merged**
