### PR TITLE
assignment 1.2

### PR DESCRIPTION
**Pull request by eswar-sai-javvaji**
Made some changes in nonstandardcode.py to make sure it is running without any errors and pushed the py script file along with 
env.yml which contained conda environment information and readme.md with necessary changes
image

### CODE REVIEW

**Review by Karthikeyaan-Kan — COMMENTED** [review]
1. Add .gitignore file to ignore .csv and other unnecessary files.

**Comment by eswar-sai-javvaji** [comment]
i have added the .gitignore file now

**Comment by eswar-sai-javvaji** [comment]
is there any more changes needed for this assignment..

**Comment by Karthikeyaan-Kan** [comment]
No changes required, submit a re-request for PR

**Comment by eswar-sai-javvaji** [comment]
can you tell me how to re-request for pr please
, does that mean raising another pr..?

**Comment by Karthikeyaan-Kan** [comment]
No, you have to simply request for re-review of this PR

**Review by Karthikeyaan-Kan — APPROVED** [review]
The PR is approved

**Pull request merged**
